### ISSUE TITLE
포켓몬 검색 후 타입 계산 결과가 출력되지 않는 포케몬 존재

### ISSUE THREAD

**Issue by ucharles** [limelee85/poke_list#9]
## 원인
- `@pkmn/data`에서 정보를 가져오지 못함
``` javascript
export function createGenList(gens, genNum) {
  const result = [];
  const genList = GetPATCH(genNum);
  // genList로 순회 >> @pkmn/data에서 가져온 포켓몬 정보 중에 showdown 자작 포켓몬 있음
  for (const key in genList) {
    result.push(
      Object.assign(
        {},
        gens.get(genNum).species.get(genList[key].name.en),
        genList[key],
      ),
    );
  }

  result.sort((a, b) => {
    if (a.name.ko < b.name.ko) {
      return -1;
    }
    if (a.name.ko > b.name.ko) {
      return 1;
    }
    return 0;
  });

  return result;
}
```

## 포켓몬 목록
- 개굴닌자
- 거다이맥스

**Comment by limelee85** [comment]
https://github.com/limelee85/poke_list/blob/a833eb4c75e013faf3317c41db8b832177c943dc/src/app/poke_data.js#L10091-L10098

poke_data.js 리스트가 [@smogon/calc](https://github.com/smogon/damage-calc/blob/86f6c87bbfed81795bfafbd7af7dc2a2fc2630a7/calc/src/data/species.ts#L8587-L8593)  를 기준으로 만들어져서 [@pkmn/data](https://github.com/pkmn/ps/blob/4a4473ce76c452b35982bd58c42029c4f5862034/dex/data/species.json#L24363-L24381) 의 key값과 일치하지 않는 건들이 존재했습니다. (거다이맥스, 리전폼, 메가진화 등)

@smogon/calc 를 import하는 것으로 수정했습니다.
